# Plubin Manager
[[plugins]]
repo = 'Shougo/dein.vim'

# Git integration
[[plugins]]
repo = 'tpope/vim-fugitive'

# Completion
# https://medium.com/vim-drops/javascript-autocompletion-on-vim-4fea7f6934e2
# hook_post_update seems to be unsupported on lazy mode. So, this plugin is here.
#[[plugins]]
#repo = 'ternjs/tern_for_vim'
#on_ft = ['javascript']
#hook_post_update = '''
#let g:dein#plugin.build = "npm i && cat << EOF > ~/.tern-project
#\\n{
#\\n  \"libs\": [
#\\n    \"browser\",
#\\n    \"ecmascript\",
#\\n    \"react\"
#\\n  ],
#\\n  \"plugins\": {
#\\n    \"node\": {},
#\\n    \"esmodules\": {}
#\\n  }
#\\n}
#\\nEOF"
#'''

# LSP
# [[plugins]]
# repo = 'prabirshrestha/async.vim'
# [[plugins]]
# repo = 'prabirshrestha/asyncomplete.vim'
# [[plugins]]
# repo = 'prabirshrestha/asyncomplete-lsp.vim'
# [[plugins]]
# repo = 'prabirshrestha/vim-lsp'
# [[plugins]]
# repo = 'mattn/vim-lsp-settings'
# merged = 0
