
## Rust
#[[plugins]]
#repo = 'rust-lang/rust.vim'
#on_ft = ['rust']

# Golang
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

# # view for scroll (this is too slow in large file)
# [[plugins]]
# repo = 'wellle/context.vim'
# on_ft = ['javascript', 'typescript']

# Json Syntax
[[plugins]]
repo = 'leshill/vim-json'
on_ft = ['javascript']

# Javascript Syntax
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

# Typescript Syntax
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

# JSX TSX Syntax
[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['javascript', 'typescript']

## Graphql Syntax
#[[plugins]]
#repo = 'jparise/vim-graphql'
#on_ft = ['javascript','graphql']

# ESLint + Flow Integration
[[plugins]]
repo = 'dense-analysis/ale'
on_ft = ['javascript', 'typescript', 'html', 'rust', 'vue']
hook_source = '''
  " w0rp/ale lints only on save
  let g:ale_lint_on_save = 1
  let g:ale_lint_on_text_changed = 0
  " use eslint only for javascript files
  let g:ale_linters = {}
  let g:ale_linters.javascript = ['eslint', 'tsserver']
  let g:ale_linters.typescript = ['eslint', 'tsserver']
  let g:ale_linters.rust = ['analyzer']
  let g:ale_linters.html = ['htmlhint']
  " completion
  let g:ale_completion_enabled = 1
  set omnifunc=ale#completion#OmniFunc
  " Put this in vimrc or a plugin file of your own.
  " After this is configured, :ALEFix will try and fix your JS code with ESLint.
  let g:ale_fixers = {
    \   'javascript': ['eslint'],
    \   'typescript': ['eslint'],
    \   'vue': ['eslint'],
    \}
'''

# vue syntax highlight
[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']
hook_source = '''
  let g:vue_pre_processors = []
'''

## Runner
#[[plugins]]
#repo = 'thinca/vim-quickrun'
#on_ft = ['javascript']

## Explorer
#[[plugins]]
#repo = 'junegunn/fzf'
#build = './install --all'
#merged = 0
#[[plugins]]
#repo = 'junegunn/fzf.vim'
#depends = 'fzf'
#on_cmd = ['FZF']
